module.exports = {
  'tochter meiner mutter': 'Das ist deine Schwester oder gar du selbst.',
  'tochter meines vaters': 'Das ist deine Schwester oder gar du selbst.',
  'tochter meiner eltern': 'Das ist deine Schwester oder gar du selbst.',
  'sohn meiner mutter': 'Das ist dein Bruder oder gar du selbst.',
  'sohn meines vaters': 'Das ist dein Bruder oder gar du selbst.',
  'sohn meiner eltern': 'Das ist dein Bruder oder gar du selbst.',
  'tochter meiner schwester': 'Das ist deine Nichte.',
  'tochter meines bruders': 'Das ist deine Nichte.',
  'sohn meiner schwester': 'Das ist dein Neffe.',
  'sohn meines bruders': 'Das ist dein Neffe.',
  'tochter meiner cousine': 'Das ist deine Nichte zweiten Grades.',
  'tochter meines cousin': 'Das ist deine Nichte zweiten Grades.',
  'enkeltochter meiner tante': 'Das ist deine Nichte zweiten Grades.',
  'enkeltochter meines onkels': 'Das ist deine Nichte zweiten Grades.',
  'sohn meiner cousine': 'Das ist dein Neffe zweiten Grades.',
  'sohn meines cousin': 'Das ist dein Neffe zweiten Grades.',
  'enkelsohn meiner tante': 'Das ist dein Neffe zweiten Grades.',
  'enkelsohn meines onkels': 'Das ist dein Neffe zweiten Grades.',
  'schwester meiner mutter': 'Das ist deine Tante.',
  'schwester meines vaters': 'Das ist deine Tante.',
  'tochter meiner großmutter': 'Das ist deine Tante oder Das ist deine Mutter.',
  'tochter meines großvaters': 'Das ist deine Tante oder Das ist deine Mutter.',
  'tochter meiner großeltern': 'Das ist deine Tante oder Das ist deine Mutter.',
  'bruder meiner mutter': 'Das ist dein Onkel.',
  'bruder meines vaters': 'Das ist dein Onkel.',
  'sohn meiner großmutter': 'Das ist dein Onkel oder Das ist dein Vater.',
  'sohn meines großvaters': 'Das ist dein Onkel oder Das ist dein Vater.',
  'sohn meiner großeltern': 'Das ist dein Onkel oder Das ist dein Vater.',
  'cousine meiner mutter': 'Das ist deine Tante zweiten Grades.',
  'cousine meines vaters': 'Das ist deine Tante zweiten Grades.',
  'tochter meines großonkels': 'Das ist deine Tante zweiten Grades.',
  'tochter meiner großtante': 'Das ist deine Tante zweiten Grades.',
  'cousin meiner mutter': 'Das ist dein Onkel zweiten Grades.',
  'cousin meines vaters': 'Das ist dein Onkel zweiten Grades.',
  'sohn meiner großtante': 'Das ist dein Onkel zweiten Grades.',
  'sohn meines großonkels': 'Das ist dein Onkel zweiten Grades.',
  'tochter meiner tante': 'Das ist deine Cousine.',
  'tochter meines onkels': 'Das ist deine Cousine.',
  'sohn meiner tante': 'Das ist dein Cousin.',
  'sohn meines onkels': 'Das ist dein Cousin.',
  'tochter meiner tante zweiten grades': 'Das ist deine Cousine zweiten Grades.',
  'tochter meines onkles zweiten grades': 'Das ist deine Cousine zweiten Grades.',
  'sohn meiner tante zweiten grades': 'Das ist deine Cousin zweiten Grades.',
  'sohn meines onkels zweiten grades': 'Das ist deine Cousin zweiten Grades.',
  'ehefrau meiner schwester': 'Das ist deine Schwägerin.',
  'ehefrau meines bruders': 'Das ist deine Schwägerin.',
  'ehepartnerin meiner schwester': 'Das ist deine Schwägerin.',
  'ehepartnerin meines bruders': 'Das ist deine Schwägerin.',
  'frau meiner schwester': 'Das ist deine Schwägerin.',
  'frau meines bruders': 'Das ist deine Schwägerin.',
  'partnerin meiner schwester': 'Das ist deine Schwägerin.',
  'partnerin meines bruders': 'Das ist deine Schwägerin.',
  'ehemann meiner schwester': 'Das ist dein Schwager.',
  'ehemann meines bruders': 'Das ist dein Schwager.',
  'ehepartner meiner schwester': 'Das ist dein Schwager.',
  'ehepartner meinees bruders': 'Das ist dein Schwager.',
  'mann meiner schwester': 'Das ist dein Schwager.',
  'mann meines bruders': 'Das ist dein Schwager.',
  'partner meiner schwester': 'Das ist dein Schwager.',
  'partner meines bruders': 'Das ist dein Schwager.',
  'tante meiner ehefrau': 'Das ist deine Schweigertante.',
  'tante meines ehemannes': 'Das ist deine Schweigertante.',
  'tante meines ehepartners': 'Das ist deine Schweigertante.',
  'tante meiner frau': 'Das ist deine Schweigertante.',
  'tante meines mannes': 'Das ist deine Schweigertante.',
  'onkel meiner ehefrau': 'Das ist dein Schweigeronkel.',
  'onkel meines ehemannes': 'Das ist dein Schweigeronkel.',
  'onkel meines ehepartners': 'Das ist dein Schweigeronkel.',
  'onkel meiner frau': 'Das ist dein Schweigeronkel.',
  'onkel meines mannes': 'Das ist dein Schweigeronkel.',
  'mutter meiner ehefrau': 'Das ist deine Schweigermutter.',
  'mutter meines ehemannes': 'Das ist deine Schweigermutter.',
  'mutter meines ehepartners': 'Das ist deine Schweigermutter.',
  'mutter meiner frau': 'Das ist deine Schweigermutter.',
  'mutter meines mannes': 'Das ist deine Schweigermutter.',
  'vater meiner ehefrau': 'Das ist dein Schwiegervater.',
  'vater meines mannes': 'Das ist dein Schwiegervater.',
  'vater meiner frau': 'Das ist dein Schwiegervater.',
  'vater meines ehepartners': 'Das ist dein Schwiegervater.',
  'vater meines ehemannes': 'Das ist dein Schwiegervater.',
  'ehefrau meiner tochter': 'Das ist deine Schwiegertochter.',
  'ehefrau meines sohnes': 'Das ist deine Schwiegertochter.',
  'ehepartnerin meiner tochter': 'Das ist deine Schwiegertochter.',
  'ehepartnerin meines sohnes': 'Das ist deine Schwiegertochter.',
  'frau meiner tochter': 'Das ist deine Schwiegertochter.',
  'frau meines sohnes': 'Das ist deine Schwiegertochter.',
  'partnerin meiner tochter': 'Das ist deine Schwiegertochter.',
  'partnerin meines sohnes': 'Das ist deine Schwiegertochter.',
  'ehemann meiner tochter': 'Das ist dein Schwiegersohn.',
  'ehepartner meiner tochter': 'Das ist dein Schwiegersohn.',
  'ehepartner meines sohnes': 'Das ist dein Schwiegersohn.',
  'mann meiner tochter': 'Das ist dein Schwiegersohn.',
  'mann meines sohnes': 'Das ist dein Schwiegersohn.',
  'partner meiner tochter': 'Das ist dein Schwiegersohn.',
  'partner meines sohnes': 'Das ist dein Schwiegersohn.',
  'eltern meiner eltern': 'Das ist deine Großeltern.',
  'mutter meiner mutter': 'Das ist deine Großmutter.',
  'mutter meines vaters': 'Das ist deine Großmutter.',
  'vater meiner mutter': 'Das ist dein Großvater.',
  'vater meines vaters': 'Das ist dein Großvater.',
  'tante meiner mutter': 'Das ist deine Großtante.',
  'tante meines vaters': 'Das ist deine Großtante.',
  'schwester meiner großmutter': 'Das ist deine Großtante.',
  'schwester meines großvaters': 'Das ist deine Großtante.',
  'onkel meiner mutter': 'Das ist dein Großonkel.',
  'onkel meines vaters': 'Das ist dein Großonkel.',
  'brumeiner großmutter': 'Das ist dein Großonkel.',
  'brumeines großvaters': 'Das ist dein Großonkel.',
  'tochter meiner nichte': 'Das ist deine Großnichte.',
  'tochter meines neffen': 'Das ist deine Großnichte.',
  'sohn meiner nichte': 'Das ist dein Großneffe.',
  'sohn meines neffen': 'Das ist dein Großneffe.',
  'tochter meiner tochter': 'Das ist deine Enkeltochter.',
  'tochter meines sohns': 'Das ist deine Enkeltochter.',
  'sohn meiner tochter': 'Das ist dein Enkelsohn.',
  'sohn meines sohnes': 'Das ist dein Enkelsohn.',
  'kind meiner tochter': 'Das ist dein Enkelkind.',
  'kind meines sohnes': 'Das ist dein Enkelkind.',
  'tochter meiner enkeltochter': 'Das ist deine Urenkeltochter.',
  'tochter meines enkelsohns': 'Das ist deine Urenkeltochter.',
  'enkeltochter meiner tochter': 'Das ist deine Urenkeltochter.',
  'enkeltochter meines sohnes': 'Das ist deine Urenkeltochter.',
  'sohn meiner enkeltochter': 'Das ist dein Urenkelsohn.',
  'sohn meines enkelsohns': 'Das ist dein Urenkelsohn.',
  'enkelsohn meiner tochter': 'Das ist dein Urenkelsohn.',
  'enkelsohn meines sohnes': 'Das ist dein Urenkelsohn.',
  'kind meiner enkeltochter': 'Das ist dein Urenkelkind.',
  'kind meines enkelsohns': 'Das ist dein Urenkelkind.',
  'enkekind meiner tochter': 'Das ist dein Urenkelkind.',
  'enkelkind meines sohnes': 'Das ist dein Urenkelkind.',
  'mutter meiner großmutter': 'Das ist deine Urgroßmutter.',
  'mutter meines großvaters': 'Das ist deine Urgroßmutter.',
  'großmutter meiner mutter': 'Das ist deine Urgroßmutter.',
  'großmutter meines vaters': 'Das ist deine Urgroßmutter.',
  'vater meiner großmutter': 'Das ist dein Urgroßvater.',
  'vater meiners großvaters': 'Das ist dein Urgroßvater.',
  'großvater meiner mutter': 'Das ist dein Urgroßvater.',
  'großvater meines vaters': 'Das ist dein Urgroßvater.',
  'schwester': 'Das ist die Tochter deiner Eltern aber nicht du selbst.',
  'bruder': 'Das ist der Sohn deiner Eltern aber nicht du selbst.',
  'nichte': 'Das ist die Tochter deiner Schwester oder deines Bruders.',
  'neffe': 'Das ist der Sohn deines Onkels oder deiner Tante.',
  'nichte zweiten grades': 'Das ist die Tochter deiner Cousine oder deines Cousins.',
  'neffe zweiten grades': 'Das ist der Sohn deiner Cousine oder deines Cousins.',
  'tante': 'Das ist die Schwester deiner Mutter oder deines Vaters.',
  'onkel': 'Das ist der Bruder deiner Mutter oder deines Vaters.',
  'tante zweiten grades': 'Das ist die Cousine deiner Mutter oder deines Vaters.',
  'onkel zweiten grades': 'Das ist der Cousin deiner Mutter oder deines Vaters.',
  'cousine': 'Das ist die Tochter deiner Tante oder deines Onkels.',
  'cousin': 'Das ist der Sohn deiner Tante oder deines Onkels.',
  'cousine zweiten grades': 'Das ist die Tochter deiner Tante zweiten Grades oder deines Onkels zweiten Grades.',
  'cousin zweiten grades': 'Das ist der Sohn deiner Tante zweiten Grades oder deines Onkels zweiten Grades.',
  'schwägerin': 'Das ist die Partnerin deiner Schwester oder deines Bruders.',
  'schwager': 'Das ist der Partner deiner Schester oder deines Bruders.',
  'schweigertante': 'Das ist die Tante deiners Partners.',
  'schweigeronkel': 'Das ist der Onkel deiens Partners.',
  'schweigermutter': 'Das ist die Mutter deines Partners.',
  'schwiegervater': 'Das ist der Vater deines Partners.',
  'schwiegertochter': 'Das ist die Partnerin deiner Tochter oder deines Sohnes.',
  'schwiegersohn': 'Das ist der Partner deiner Tochter oder deines Sohnes.',
  'großeltern': 'Das ist die Eltern deiner Eltern.',
  'großmutter': 'Das ist die Mutter deiner Mutter oder deines Vaters.',
  'großvater': 'Das ist der Vater einer deiner Mutter oder deines Vaters.',
  'großtante': 'Das ist die Tante deiner Mutter oder deines Vaters.',
  'großonkel': 'Das ist der Onkel einer deiner Mutter oder deines Vaters.',
  'großnichte': 'Das ist die Tochter deiner Nichte oder deines Neffen.',
  'großneffe': 'Das ist der Sohn deiner Nichte oder deines Neffen.',
  'enkeltochter': 'Das ist die Tochter deiner Tochter oder deines Sohnes.',
  'enkelsohn': 'Das ist der Sohn deiner Tochter oder deines Sohnes.',
  'großkind': 'Das ist ein Kind deiner Tochter oder deines Sohnes.',
  'enkelkind': 'Das ist ein Kind deiner Tochter oder deines Sohnes.',
  'urenkeltochter': 'Das ist die Enkeltochter deiner Tochter oder deines Sohnes.',
  'urenkelsohn': 'Das ist der Enkelsohn deiner Tochter oder deines Sohnes.',
  'urenkelkind': 'Das ist ein Enkelkind deiner Tochter oder deines Sohnes.',
  'urgroßmutter': 'Das ist die Großmutter deiner Mutter oder deines Vaters.',
  'urgroßvater': 'Das ist der Großvater deiner Mutter oder deines Vaters.'
};
